# Generated by Django 4.2.2 on 2023-06-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_desc', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('product_picone', models.ImageField(upload_to='static/images')),
                ('product_pictwo', models.ImageField(upload_to='static/images')),
                ('product_picthree', models.ImageField(upload_to='static/images')),
                ('product_picfour', models.ImageField(upload_to='static/images')),
                ('Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.categories')),
            ],
        ),
    ]
