# Generated by Django 4.2.2 on 2023-06-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_size_remove_products_size_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='products',
            name='size_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_with_size_four', to='ecom.size'),
        ),
        migrations.AddField(
            model_name='products',
            name='size_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_with_size_one', to='ecom.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='size_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_with_size_three', to='ecom.size'),
        ),
        migrations.AddField(
            model_name='products',
            name='size_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_with_size_two', to='ecom.size'),
        ),
    ]
