# Generated by Django 4.2.2 on 2023-06-30 06:03

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_remove_products_size_products_size_four_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_picfour',
            field=models.ImageField(upload_to=ecom.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_picone',
            field=models.ImageField(upload_to=ecom.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_picthree',
            field=models.ImageField(upload_to=ecom.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_pictwo',
            field=models.ImageField(upload_to=ecom.models.get_image_path),
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(to='ecom.color'),
        ),
    ]
