# Generated by Django 4.2.2 on 2023-06-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_remove_products_colors_products_color_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(to='ecom.color'),
        ),
    ]
