# Generated by Django 4.2.2 on 2023-06-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_color_remove_products_color_products_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
